project:
  type: book
  output-dir: docs

book:
  title: "ADA Notebook Library"
  author: "Team ADA"
  date: "2023-04-28"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  repo-url: https://github.com/NFDI4Culture/ada-cp-notebook-library
  repo-actions: [edit]
  downloads: [pdf]  

bibliography: references.bib

format:
  html:
    code-fold: true
    code-overflow: wrap
    theme: minty
  pdf:
    documentclass: book



